repos:
-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
    -   id: go-unit-tests
-   repo: local
    hooks:
      - id: lint
        name: golangci-lint
        entry: "bash golangci-lint.sh"
        language: system
        verbose: true
      

