# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 1m

linters:
  disable-all: true
  enable:
    - gocyclo
    - govet
    - whitespace
    - bodyclose
    - gofmt
