version: "3.7"

services:

  postgres:
    image: postgres:14.5
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - /opt/databases/smurl_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1110
      POSTGRES_DB: test
    networks:
      - smurlnet

  smurl:
    image: smurl:latest
    container_name: smurl
    build: .
   
    restart: always
    ports:
      - 1234:1234
    volumes:
      - ./config:/app/config
      - ./static:/app/static
    environment:
      DATABASE_URL: "postgres://postgres:1110@postgres/test?sslmode=disable"
    depends_on:
      - postgres
    networks:
      - smurlnet

networks:
  smurlnet: