// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/sanyarise/smurl/internal/models"
)

// MockSmurlStore is a mock of SmurlStore interface.
type MockSmurlStore struct {
	ctrl     *gomock.Controller
	recorder *MockSmurlStoreMockRecorder
}

// MockSmurlStoreMockRecorder is the mock recorder for MockSmurlStore.
type MockSmurlStoreMockRecorder struct {
	mock *MockSmurlStore
}

// NewMockSmurlStore creates a new mock instance.
func NewMockSmurlStore(ctrl *gomock.Controller) *MockSmurlStore {
	mock := &MockSmurlStore{ctrl: ctrl}
	mock.recorder = &MockSmurlStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSmurlStore) EXPECT() *MockSmurlStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSmurlStore) Create(ctx context.Context, smurl models.Smurl) (*models.Smurl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, smurl)
	ret0, _ := ret[0].(*models.Smurl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSmurlStoreMockRecorder) Create(ctx, smurl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSmurlStore)(nil).Create), ctx, smurl)
}

// FindURL mocks base method.
func (m *MockSmurlStore) FindURL(ctx context.Context, smallUrl string) (*models.Smurl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindURL", ctx, smallUrl)
	ret0, _ := ret[0].(*models.Smurl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindURL indicates an expected call of FindURL.
func (mr *MockSmurlStoreMockRecorder) FindURL(ctx, smallUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindURL", reflect.TypeOf((*MockSmurlStore)(nil).FindURL), ctx, smallUrl)
}

// ReadStat mocks base method.
func (m *MockSmurlStore) ReadStat(ctx context.Context, adminUrl string) (*models.Smurl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadStat", ctx, adminUrl)
	ret0, _ := ret[0].(*models.Smurl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadStat indicates an expected call of ReadStat.
func (mr *MockSmurlStoreMockRecorder) ReadStat(ctx, adminUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadStat", reflect.TypeOf((*MockSmurlStore)(nil).ReadStat), ctx, adminUrl)
}

// UpdateStat mocks base method.
func (m *MockSmurlStore) UpdateStat(ctx context.Context, smurl models.Smurl) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStat", ctx, smurl)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStat indicates an expected call of UpdateStat.
func (mr *MockSmurlStoreMockRecorder) UpdateStat(ctx, smurl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStat", reflect.TypeOf((*MockSmurlStore)(nil).UpdateStat), ctx, smurl)
}
