// Code generated by MockGen. DO NOT EDIT.
// Source: internal/helpers/helpers.go

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHelper is a mock of Helper interface.
type MockHelper struct {
	ctrl     *gomock.Controller
	recorder *MockHelperMockRecorder
}

// MockHelperMockRecorder is the mock recorder for MockHelper.
type MockHelperMockRecorder struct {
	mock *MockHelper
}

// NewMockHelper creates a new mock instance.
func NewMockHelper(ctrl *gomock.Controller) *MockHelper {
	mock := &MockHelper{ctrl: ctrl}
	mock.recorder = &MockHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelper) EXPECT() *MockHelperMockRecorder {
	return m.recorder
}

// CheckURL mocks base method.
func (m *MockHelper) CheckURL(longURL string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckURL", longURL)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckURL indicates an expected call of CheckURL.
func (mr *MockHelperMockRecorder) CheckURL(longURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckURL", reflect.TypeOf((*MockHelper)(nil).CheckURL), longURL)
}

// GetIP mocks base method.
func (m *MockHelper) GetIP(r *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIP", r)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIP indicates an expected call of GetIP.
func (mr *MockHelperMockRecorder) GetIP(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIP", reflect.TypeOf((*MockHelper)(nil).GetIP), r)
}

// RandString mocks base method.
func (m *MockHelper) RandString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RandString")
	ret0, _ := ret[0].(string)
	return ret0
}

// RandString indicates an expected call of RandString.
func (mr *MockHelperMockRecorder) RandString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RandString", reflect.TypeOf((*MockHelper)(nil).RandString))
}
